### ISSUE TITLE
GPL3 license violation

### ISSUE THREAD

**Issue by demanuPL** [PikaOS-Linux/pkg-ananicy-rules#1]
since you are using the cachyos code released under the GPL3 license please comply with the license under which the code is released. It is not allowed to change the software to MIT in case of using someone else's code under GPL3. Also its violation of Github TOS.

thank you and please resolve this licence violation ASAP

**Comment by ferrreo** [comment]
This is a package build script, this repo contains no cachyos code so it is not relicensing anything. This would be classed as an independent work as per the GPL.
